
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2.1'
services:
  batch:
    build:
      context: batch
    image: openmrs-fhir-analytics/batch-job:latest
    #restart: "always"
    network_mode: host
    container_name: batch-cloud
    healthcheck:
      test: "exit 0"
    environment:
      - SERVER_URL=https://isanteplusdemo.com/openmrs
      - SEARCH_LIST=Patient,Encounter,Observation
      - BATCH_SIZE=20
      - TARGET_PARALLELISM=20
      - SOURCE_PW=Admin123
      - SOURCE_USERNAME=admin
      - GCP_FHIR_STORE=projects/PROJECT/locations/LOCATION/datasets/DATASET/fhirStores/FHIRSTORENAME

  streaming-binlog: # To run independently: docker-compose up --build streaming-binlog
    build:
      context: streaming-binlog
    image: openmrs-fhir-analytics/streaming-pipeline:${DEBEZIUM_VERSION}
    container_name: streaming-pipeline
    network_mode: host
    healthcheck:
      test: "exit 0"
    volumes:
      - ./dbz:/tmp
    environment:
      - JAVA_MAIN_CLASS=org.openmrs.analytics.Runner
      - JAVA_OPTIONS=-Ddatabase.hostname=localhost -Ddatabase.port=3306 -Ddatabase.user=root -Ddatabase.password=debezium
                     -Ddatabase.dbname=mysql -Ddatabase.schema=openmrs -Ddatabase.serverId=77 -Ddatabase.offsetStorage=/tmp/offset.dat
                     -Ddatabase.databaseHistory=/tmp/dbhistory.dat -Dopenmrs.username=admin -Dopenmrs.password=Admin123
                     -Dopenmrs.serverUrl=http://localhost:8099 -Dopenmrs.fhirBaseEndpoint=/openmrs/ws/fhir2/R4
                     -Dcloud.gcpFhirStore=projects/PROJECT/locations/LOCATION/datasets/DATASET/fhirStores/FHIRSTORENAME

  streaming-atomfeed:
    container_name: streaming-atomfeed
    hostname: streaming-atomfeed
    build:
      context: ./
      dockerfile: ./streaming-atomfeed/org.Dockerfile
    healthcheck:
      test: "exit 0"
    environment:
      - SOURCE_URL=https://isanteplusdemo.com/openmrs
      - SOURCE_FEED_ENDPOINT=/ws/atomfeed
      - SOURCE_FHIR_ENDPOINT=/ws/fhir2/R4
      - SOURCE_PW=Admin123
      - SOURCE_USERNAME=admin
      - SINK_USERNAME=shr
      - SINK_PASSWORD=shr
      - SINK_URL=http://sedish-haiti.org:5001/SHR/fhir
    restart: unless-stopped
  streaming-atomfeed-ii:
    container_name: streaming-atomfeed-ii
    hostname: streaming-atomfeed-ii
    build:
      context: ./
      dockerfile: ./streaming-atomfeed/org.Dockerfile
      args:
        USERNAME: ${RELEASE_USERNAME}
        TOKEN: ${RELEASE_TOKEN}
    healthcheck:
      test: "exit 0"
    environment:
      - SOURCE_URL=https://isanteplus-test.sedish-haiti.org/openmrs
      - SOURCE_FEED_ENDPOINT=/ws/atomfeed
      - SOURCE_FHIR_ENDPOINT=/ws/fhir2/R4
      - SOURCE_PW=Admin123
      - SOURCE_USERNAME=admin
      - SINK_USERNAME=shr
      - SINK_PASSWORD=shr
      - SINK_URL=http://sedish-haiti.org:5001/SHR/fhir
    restart: unless-stopped
    networks: 
      - sedish
    
  streaming-atomfeed-db:
    container_name: streaming-atomfeed-db
    hostname: streaming-atomfeed-db
    image: mysql:5.7
    healthcheck:
      test: "exit 0"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=fhir
      - MYSQL_PASSWORD=fhiranalytics
      - MYSQL_DATABASE=atomfeed_client
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
      - ./utils/dbdump/create_db.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  m2repo:
  db:
networks:
  sedish:
    external: true
    name: shared-health-record_sedish
