spring:
  profiles:
    active: dstu3
hapi:
  fhir:
    tester:
      -
        id: main
        name: Local
        server_address: 'http://localhost:8098/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
